Attribute VB_Name = "CodeListedErrors"
Public Const FootingToDoMsgCodelist = "StructFootingToDoMessages"

Public Const TDL_SYMFILE_NOTACCESSSIBLE = 1
Public Const TDL_COMBINEDFTG_REQDMIN_TWOMEMBS = 2
Public Const TDL_BOSLEVEL_SUPPORTEDMEMBS_TOBESAME = 3
Public Const TDL_FTGMACROS_MISSING_SUPPORTED_MEMB = 4
Public Const TDL_FTGMACROS_MISSING_SUPPORTING_PLANE = 5
Public Const TDL_FTGMACROS_INVALID_PIERHEIGHT = 6
Public Const TDL_FTGMACROS_INSUFFICIENT_INPUTS = 7
Public Const TDL_FTGMACROS_BOTTOMPLANE_NOTVALID = 8
Public Const TDL_FTGMACROS_BOTTOMPLANE_NOTVALID_CANNOTCOMPUTE = 9
Public Const TDL_FTGMACROS_BOTTOMPLANE_CANNOTCOMPUTE_SLABHEIGHT = 10
Public Const TDL_FTGMACROS_INVALID_BOTTTOMPLANE_CANNOTCOMPUTE = 11
Public Const TDL_FTGMACROS_OCTGROUT_NOTSUPPORTED = 12
Public Const TDL_FTGMACROS_PIERHEIGHT_INVALID_CHECK = 13
Public Const TDL_FTGMACROS_NOTSUPPPORT_SUPPMEMBS = 14

