Attribute VB_Name = "CodeListedErrors"
'*******************************************************************
'
'Copyright (C) 2006 Intergraph Corporation. All rights reserved.
'
'File : CodeListedErrors.bas
'
'Author : RP
'
'Description :
'    Module for mapping codelist value for errors to constants
'
'History:
'   03-Nov-2006   RP   Removed 19 and 32 as they are duplicates of 10 and 11 (TR#109353)
'
'*****************************************************************************************************************


Public Const FCToDoMsgCodelist = "StructFCToDoMessages"

Public Const TDL_FCMACROS_AXISALONG_INVALIDPOINT = 1
Public Const TDL_FCMACROS_AXISALONG_PREVIOUSCONN_NOTREMOVED = 2
Public Const TDL_FCMACROS_AXISALONG_MISSING_SUPPORTINGMEMB_INFORM = 3
Public Const TDL_FCMACROS_AXISALONG_CHANGE_CONN = 4
Public Const TDL_FCMACROS_AXISALONG_SAMEMEMB_FORBOTH = 5
Public Const TDL_FCMACROS_AXISALONG_REVERIFIED_INVALID = 6

Public Const TDL_FCMACROS_AXISCOLI_MEMS_COLINEAR = 7
Public Const TDL_FCMACROS_AXISCOLI_MISSING_INPUT = 8
Public Const TDL_FCMACROS_AXISCOLI_NOTRELATED_MEMBS = 9
Public Const TDL_FCMACROS_AXISCOLI_SAMEMEMBS_FORBOTH = 10
Public Const TDL_FCMACROS_AXISCOLI_SUPPORTED_TOOFAR = 11
Public Const TDL_FCMACROS_AXISCOLI_SUPPORTING_TOOFAR = 12
Public Const TDL_FCMACROS_AXISCOLI_NOTCONSTR_BYSAME = 13
Public Const TDL_FCMACROS_AXISCOLI_INVALID_ENDPORT = 14
Public Const TDL_FCMACROS_AXISCOLI_PERMISSIONGROUP_SAME = 15
Public Const TDL_FCMACROS_AXISCOLI_PREVIOUSREL_NOTREMOVED = 16
Public Const TDL_FCMACROS_AXISCOLI_MISSING_SUPPRTING_INFORM = 17
Public Const TDL_FCMACROS_AXISCOLI_RELATEDTO_OTHER = 18

Public Const TDL_FCMACROS_AXISCOLI_REVERIFIED_INVALID = 20

Public Const TDL_FCMACROS_AXISEND_MISSING_INPUT = 21
Public Const TDL_FCMACROS_AXISEND_NOTRELATED_MEMBS = 22
Public Const TDL_FCMACROS_AXISEND_SUPPORTING_SUPPORTED_SAME = 23
Public Const TDL_FCMACROS_AXISEND_INVALID_ENDPORT = 24
Public Const TDL_FCMACROS_AXISEND_ENDCONN_INCONSISTENT = 25
Public Const TDL_FCMACROS_AXISEND_ENDPORT_DIFF_MEMBS = 26
Public Const TDL_FCMACROS_AXISEND_SAME_PERMISSIONGROUP = 27
Public Const TDL_FCMACROS_AXISEND_PREVIOUSCONN_NOTREMOVED = 28
Public Const TDL_FCMACROS_AXISEND_MISSING_INFORMATION = 29
Public Const TDL_FCMACROS_AXISEND_NOTRELATED_SUPPMEMB = 30
Public Const TDL_FCMACROS_AXISEND_NOTFIND_SUPPORTEDMEMB = 31
Public Const TDL_FCMACROS_AXISEND_REVERIFIED_INVALID = 33
Public Const TDL_FCMACROS_AXISEND_SUPPORTEDENDS_SHARESINGLE_JOINT = 34

Public Const TDL_FCMACROS_CENTER_MISSING_INPUT = 35
Public Const TDL_FCMACROS_CENTER_NOTRELATED_SUPPORTING = 36
Public Const TDL_FCMACROS_CENTER_NOTRELATED_SUPPORTED = 37
Public Const TDL_FCMACROS_CENTER_SUPPORTED_INVALIDPOINT = 38
Public Const TDL_FCMACROS_CENTER_NOTREMOVED_PREVIOUSCONN = 39
Public Const TDL_FCMACROS_CENTER_MISSING_INFORMATION_SUPPPORTING = 40
Public Const TDL_FCMACROS_CENTER_NOTRELATED_SUPPORTINGMEMBS = 41
Public Const TDL_FCMACROS_CENTER_SAMEMEMBS_BOTH = 42
Public Const TDL_FCMACROS_CENTER_REVERIFIED_INVALID = 43

Public Const TDL_FCMACROS_CHEVRON_MISSING_INPUT = 44
Public Const TDL_FCMACROS_CHEVRON_NOTRELATED_BRACEMEMBS = 45
Public Const TDL_FCMACROS_CHEVRON_NOTRELATED_SUPPORTING = 46
Public Const TDL_FCMACROS_CHEVRON_PREVIOUSCONN_NOTREMOVED = 47
Public Const TDL_FCMACROS_CHEVRON_MISSING_SUPPORTING_INFORMATION = 48
Public Const TDL_FCMACROS_CHEVRON_NORELATED_SUPPORTING = 49
Public Const TDL_FCMACROS_CHEVRON_SAMEMEMBS_BOTH = 50

Public Const TDL_FCMACROS_FLUSH_MISSING_INPUT = 51
Public Const TDL_FCMACROS_FLUSH_MISSING_SUPPORTED_MEMBS = 52
Public Const TDL_FCMACROS_FLUSH_MISSING_SUPPORTING_MEMBS = 53
Public Const TDL_FCMACROS_FLUSH_MEMBER_INVALID_POINT = 54
Public Const TDL_FCMACROS_FLUSH_PREVIOUSCONN_NOTREMOVED = 55
Public Const TDL_FCMACROS_FLUSH_MISSING_INFORMATION_SUPPORTING = 56
Public Const TDL_FCMACROS_FLUSH_NOTRELATED_SUPPORTING = 57
Public Const TDL_FCMACROS_FLUSH_SAMEMEBS_BOTH = 58
Public Const TDL_FCMACROS_FLUSH_REVERIFIED_INVALID = 59

Public Const TDL_FCMACROS_FRAME_PREVIOUSREL_NOTCLEAR = 60
Public Const TDL_FCMACROS_FRAME_CANNOTUSE_ASOBJ1 = 61
Public Const TDL_FCMACROS_FRAME_CANNOTUSE_ASOBJ2 = 62

Public Const TDL_FCMACROS_SEATED_MISSING_INPUT = 63
Public Const TDL_FCMACROS_SEATED_MISSING_SUPPORTEDMEMBS = 64
Public Const TDL_FCMACROS_SEATED_MISSING_SUPPORTING_MEMBS = 65
Public Const TDL_FCMACROS_SEATED_INVALID_PORT_SUPPORTED = 66
Public Const TDL_FCMACROS_SEATED_PREVIOUSCONN_NOTREMOVED = 67
Public Const TDL_FCMACROS_SEATED_MISSING_SUPPORTED_INFORMATION = 68
Public Const TDL_FCMACROS_SEATED_NOTRELATED_SUPPORTINGMEMBS = 69
Public Const TDL_FCMACROS_SEATED_SAMEMEMBS_FORBOTH = 70
Public Const TDL_FCMACROS_SEATED_REVERIFIED_INVALID = 71

Public Const TDL_FCMACROS_SURFACE_MISSSING_INPUT = 72
Public Const TDL_FCMACROS_SURFACE_MISSING_MEMBS = 73
Public Const TDL_FCMACROS_SURFACE_MISSING_SURFACE = 74
Public Const TDL_FCMACROS_SURFACE_NOTRELATED_VALIDSURFACE = 75
Public Const TDL_FCMACROS_SURFACE_REVERIFIED_INVALID = 76


Public Const TDL_FCMACROS_VC_MISSING_REQDINPUT = 77
Public Const TDL_FCMACROS_VC_MISSING_BRACEMEMBS = 78
Public Const TDL_FCMACROS_VC_MISSING_SUPPORTINGMEMB = 79
Public Const TDL_FCMACROS_VC_MISSING_TWO_MEMBS = 80
Public Const TDL_FCMACROS_VC_EXPECTED_BRACEJOINT = 81
Public Const TDL_FCMACROS_VC_NOTPOINTON_RELATED = 82
Public Const TDL_FCMACROS_VC_INVALID_RELATIONSHIP = 83
Public Const TDL_FCMACROS_VC_PREVIOUSCONN_NOTREMOVED = 84
Public Const TDL_FCMACROS_VC_MISSING_SUPPORTING_MEMBS = 85
Public Const TDL_FCMACROS_VC_NOTRELATED_SUPPORTINGMEMB = 86
Public Const TDL_FCMACROS_VC_MISSING_SUPPRTINGMEMBS = 87
Public Const TDL_FCMACROS_VC_NOTRELATED_SECOND_SUPPORTING = 88
Public Const TDL_FCMACROS_VC_USING_BRACEMEMB_INCORRECTLY = 89
Public Const TDL_FCMACROS_VC_SAMEMEMBS_FORBOTH = 90
Public Const TDL_FCMACROS_VC_CANNOTIDENTIFY_END = 91
Public Const TDL_FCMACROS_VC_BRACEEND_NOTNEAR_SUPPORTING = 92
Public Const TDL_FCMACROS_VC_BRACEEND_NOTNEAR_SEC_SUPPORTING = 93
Public Const TDL_FCMACROS_VC_PORT_UNABLETO_GETMEMBS = 94
Public Const TDL_FCMACROS_VC_UNKNOWNOBECT = 95


Public Const TDL_FCMACROS_AXISCOLI_SUPPORTEDNOT_ATEND = 97
Public Const TDL_FCMACROS_CHEVRON_NOTDEFINED_SUPPORTED = 98
Public Const TDL_FCMACROS_UNSUPP_MISSING_REQDDATA = 99
Public Const TDL_FCMACROS_UNSUPP_LINKEDTO_MORETHANONE = 100
Public Const TDL_FCMACROS_UNSUPP_MISSING_PARENT = 101
Public Const TDL_FCMACROS_UNSUPP_NOTLINKED_MEMBS = 102
Public Const TDL_FCMACROS_AXISCOLI_REL_INCONSISTANT = 103
Public Const TDL_FCMACROS_AXISCOLI_REL_DIFF_ENDPORT = 104
Public Const TDL_FCMACROS_AXISCOLI_CANNOTFIND_SUPPMEMBS = 105
Public Const TDL_FCMACROS_GAP_CPLINES_DO_NOT_INTERSECT = 106
Public Const TDL_FCMACROS_GAP_COLINEAR_MEMBERS = 107
Public Const TDL_FCMACROS_GAP_MEMBERS_INVALID = 108
Public Const TDL_FCMACROS_GAP_UNEXPECTED_ERROR = 109
Public Const TDL_FCMACROS_GAP_RADIAL_COPLANAR_MEMBERS = 110
