Attribute VB_Name = "CodeListedErrors"
Public Const SCToDoMsgCodelist = "StructSCToDoMessages"

Public Const TDL_SPLITMACROS_UNEXPECTED_ERROR = 1
Public Const TDL_SPLITMACROS_NOVALID_INTERSECTION = 2
Public Const TDL_SPLITMACROS_UNEXP_REFCOLLCOUNT = 3
Public Const TDL_SPLITMACROS_NOPARENT1 = 4
Public Const TDL_SPLITMACROS_NOSECOND_PARENT = 5
Public Const TDL_SPLITMACROS_UNKNOWNTYPE_PARENT2 = 6
Public Const TDL_SPLITMACROS_SCNDPARENT_SAMEAS_FSTPARENT = 7
Public Const TDL_SPLITMACROS_INVALID_POINT = 8

