Attribute VB_Name = "MarineLibraryConstants"
'
'
' IJWeldingSymbol attribute names -- total 34
Public Const PRIMARY_SIDE_SYMBOL As String = "PrimarySideSymbol"
Public Const SECONDARY_SIDE_SYMBOL As String = "SecondarySideSymbol"
Public Const PRIMARY_SIDE_GROOVE As String = "PrimarySideGroove"
Public Const SECONDARY_SIDE_GROOVE As String = "SecondarySideGroove"
Public Const PRIMARY_SIDE_GROOVE_SIZE As String = "PrimarySideGrooveSize"
Public Const SECONDARY_SIDE_GROOVE_SIZE As String = "SecondarySideGrooveSize"
Public Const PRIMARY_SIDE_ACTUAL_THROAT_THICKNESS As String = "PrimarySideActualThroatThickness"
Public Const SECONDARY_SIDE_ACTUAL_THROAT_THICKNESS As String = "SecondarySideActualThroatThickness"
Public Const PRIMARY_SIDE_NOMINAL_THROAT_THICKNESS As String = "PrimarySideNominalThroatThickness"
Public Const SECONDARY_SIDE_NOMINAL_THROAT_THICKNESS As String = "SecondarySideNominalThroatThickness"
Public Const FIELD_WELD As String = "FieldWeld"
Public Const ALL_AROUND As String = "AllAround"
Public Const PRIMARY_SIDE_SUPPLEMENTARY_SYMBOL As String = "PrimarySideSupplementarySymbol"
Public Const SECONDARY_SIDE_SUPPLEMENTARY_SYMBOL As String = "SecondarySideSupplementarySymbol"
Public Const TAIL_NOTES As String = "TailNotes"
Public Const TAIL_NOTE_IS_REFERENCE As String = "TailNoteIsReference"
Public Const PRIMARY_SIDE_LENGTH As String = "PrimarySideLength"
Public Const SECONDARY_SIDE_LENGTH As String = "SecondarySideLength"
Public Const PRIMARY_SIDE_PITCH As String = "PrimarySidePitch"
Public Const SECONDARY_SIDE_PITCH As String = "SecondarySidePitch"
Public Const PRIMARY_SIDE_DIAMETER As String = "PrimarySideDiameter"
Public Const SECONDARY_SIDE_DIAMETER As String = "SecondarySideDiameter"
Public Const PRIMARY_SIDE_CONTOUR As String = "PrimarySideContour"
Public Const SECONDARY_SIDE_CONTOUR As String = "SecondarySideContour"
Public Const PRIMARY_SIDE_FINISH_METHOD As String = "PrimarySideFinishMethod"
Public Const SECONDARY_SIDE_FINISH_METHOD As String = "SecondarySideFinishMethod"
Public Const PRIMARY_SIDE_ROOT_OPENING As String = "PrimarySideRootOpening"
Public Const SECONDARY_SIDE_ROOT_OPENING As String = "SecondarySideRootOpening"
Public Const PRIMARY_SIDE_GROOVE_ANGLE As String = "PrimarySideGrooveAngle"
Public Const SECONDARY_SIDE_GROOVE_ANGLE As String = "SecondarySideGrooveAngle"
Public Const PRIMARY_SIDE_NUMBER_OF_WELDS As String = "PrimarySideNumberOfWelds"
Public Const SECONDARY_SIDE_NUMBER_OF_WELDS As String = "SecondarySideNumberOfWelds"
Public Const PRIMARY_SIDE_ACTUAL_LEG_LENGTH As String = "PrimarySideActualLegLength"
Public Const SECONDARY_SIDE_ACTUAL_LEG_LENGTH As String = "SecondarySideActualLegLength"

